### ISSUE TITLE
Add follow support for JioChat

### ISSUE THREAD

**Issue by nicpottier** [nyaruka/courier#117]
`{"ToUserName":"600000000598","FromUserName":"1526477381","CreateTime":1518775486606,"MsgType":"event","Event":"subscribe"}`

**Comment by norkans7** [comment]
I think this is handled already by https://github.com/nyaruka/courier/blob/master/handlers/jiochat/jiochat.go#L131

**Comment by nicpottier** [comment]
right you are!
