### ISSUE TITLE
WhatsApp Update v1

### ISSUE THREAD

**Issue by johncordeiro** [nyaruka/courier#153]
These are the updates on the v1 API:

- Endpoints updated according to RESTful API best practices, for example, send messages endpoint was updated from `{URL}/api/rest_send.php` to `{URL}/v1/messages`
- Payload node was replaced to the body itself
- Necessary use of user accounts and access tokens for all API calls
- The REST API has a single webhook where all types of callbacks will be sent.

PR welcome here?

**Comment by nicpottier** [comment]
@johncordeiro should I assume this isn't coming from you guys?

**Comment by nicpottier** [comment]
We added this.
