### ISSUE TITLE
Bind to a specific interface or IP address

### ISSUE THREAD

**Issue by idevsoftware** [nyaruka/courier#159]
Hi, is there any way to specify an IP address or network interface for courier to bind to? right now it listens on all interfaces, both IPv4 and v6.

If not currently implemented are there any plans to add this in the foreseeable future?

**Comment by nicpottier** [comment]
We don't have plans to add it but would accept a PR for that.

**Comment by idevsoftware** [comment]
Ok, I'm not much of a go-er but I can learn.

**Comment by idevsoftware** [comment]
I'm sending a PR for this
