### ISSUE TITLE
BuildDownloadMediaRequest interface spec is incorrect

### ISSUE THREAD

**Issue by smn** [nyaruka/courier#181]
The interface expects 3 arguments `context`, `channel`, and `string`.
https://github.com/nyaruka/courier/blob/f41d63f4a89614422dacec3d077c9938db07ca2d/handler.go#L36

Each of the implementations expects 4 arguments, the 3 listed above and also a `courier.Backend` as a second positional argument.

https://github.com/nyaruka/courier/blob/4c3ef8f1f894ae709e5686bdc964b65dac0bae9b/handlers/jiochat/jiochat.go#L309

I came across this while trying to get the WhatsApp handler in #179 to download media objects with an Authorization token set.

**Comment by smn** [comment]
There's a fix for this in #179.

**Comment by nicpottier** [comment]
Thanks, ya, golang interfaces can be funny that way in that drift can occur. We should add a type assertion for the whatsapp channel type to prevent this from drifting again in the future.
