### ISSUE TITLE
Is S3 hardcoded?

### ISSUE THREAD

**Issue by pangoSE** [nyaruka/courier#249]
The readme says:
"For writing of message attachments, Courier needs access to an S3 bucket, you can configure access to your bucket via:"

Does this mean that S3 is hardcoded?
How can I configure local storage instead?

**Comment by nicpottier** [comment]
You can use services that expose an S3 API for local storage.

https://github.com/minio/minio/ is one example, there are many others.

**Comment by pangoSE** [comment]
Thanks a lot, this was very helpful. I suggest you hint at this in the README.
