### ISSUE TITLE
Connecting to rapidpro

### ISSUE THREAD

**Issue by pangoSE** [nyaruka/courier#250]
Hi
I'm trying to set up courier with a production rapidpro instance.
Could you detail in the readme how to do that?
E.g. does courier need its own database only or only read/write in the rapidpro database?
What tables does it need access to?
What is the recommended setup? Using the temba dbuser setup with rapidpro?

**Comment by nicpottier** [comment]
From README:
> COURIER_DB: Details parameters used to connect to the Postgres RapidPro database (ex: postgres://textit:fooman@rds.courier.io/5432/textit)

It is the RapidPro db. Up to you if you want to use the same user or not, but yes obviously it writes and reads.
