### ISSUE TITLE
Courier not listening on port? Missing error?

### ISSUE THREAD

**Issue by pangoSE** [nyaruka/courier#251]
Hi
I started courier with the config below and got this:
$ sudo lsof -i
courier   15683 bl-rapidpro-dev    4u  IPv4 510582      0t0  TCP localhost:41956->localhost:postgresql (ESTABLISHED)
courier   15683 bl-rapidpro-dev    6u  IPv4 510587      0t0  TCP localhost:45066->localhost:6379 (ESTABLISHED)
courier   15683 bl-rapidpro-dev    8u  IPv6 510597      0t0  TCP *:http-alt (LISTEN)

the output from courier was:
ERRO[0000] s3 bucket not reachable                       comp=backend error="Forbidden: Forbidden\n\tstatus code: 403, request id: FAF3956A7BC77C26, host id: VqcKi03sADHyhKgsd75i8kOiqIdmIPrcaJrEbfU2HLk3IkspLwfN34jqvCc/jYVGOgxIy9uZEW8=" state=starting

config:

> # What backend to use for looking up and writing data
> backend = "rapidpro"
> 
> # What port courier will run on
> port = 8080
> 
> # Our database connection string, right now only Postgres is supported
> # postgresql://[user[:password]@][netloc][:port][/dbname][?param1=value1&...]
> # We don't need ssl because the DB is on the local machine
> db = "postgres://courier:password@localhost/courier?sslmode=disable"
> 
> # Our redis connection string, path is our database. Rapid Pro uses 15 for the database (or 10 when testing) 
> redis = "redis://localhost:6379/15"
> 
> # Our spool directory for storing messages when Redis is down, this must exist and be writeable
> spool_dir = "/var/spool/courier"
> 
> # Our AWS access credentials
> #aws_access_key_id = "missing_aws_access_key_id"
> #aws_secret_access_key = "missing_aws_secret_access_key"
> 
> # The region our AWS bucket is in
> #s3_region = "us-east-2"
> 
> # The S3 bucket we will write our media files to
> #s3_media_bucket = "courier-test"
> 
> # prefix to our filenames for media (files will be named after the msg uuid)
> #s3_media_prefix = "media"
> 
> # the DSN token for reporting errors to sentry
> sentry_dsn = ""
>

**Comment by nicpottier** [comment]
Starting with `-debug-conf` will give you some output on what config values were actually used. Would also recommend upping the log level to debug. This obviously works as this is run in production by lots of people so I'm guessing you have a configuration problem somewhere.

Note that if your `COURIER_ADDRESS` is `127.0.0.1` it will not accept connections from the outside, use `0.0.0.0` for that.

**Comment by pangoSE** [comment]
Thanks for the quick response. I suppose the missing S3 connection (I commented it out as you see in my config above) is the cause of this. 
I still think it is a bug that it does not inform that it could not start. Maybe it could even exit if no S3 connection is set up.

**Comment by nicpottier** [comment]
Not everybody needs / wants attachments, so S3 is optional. It does log an error. We also don't want courier not to start because of a temporary problem, which is why we log and continue.

**Comment by pangoSE** [comment]
Thanks for the information. I got it to work by adding address and domain to the config seen above.
I submitted a PR to add these to the default courier.toml.
