### ISSUE TITLE
Updating of Contact name on WhatsApp

### ISSUE THREAD

**Issue by rudigiesler** [nyaruka/courier#255]
In the webhook that we receive from WhatsApp for an inbound message, there is a `contacts` key that has a list of contacts with information, including their WhatsApp name, eg:
```
{
  "contacts": [
    {"profile": {"name": "Example Name"}, "wa_id": "1234567890"}
  ],
  "messages": ...
}
```

We could use this name information in RapidPro.

What would be the feeling of updating the contact's name field with this information, if the name field is currently null?

![image](https://user-images.githubusercontent.com/8234653/64532002-f1bacf00-d310-11e9-97fe-cd0c78779b10.png)

**Comment by rowanseymour** [comment]
Wouldn't we already have set the name from a channel type that provides this kind of information? E.g. the contact name is set when they were created on their first interaction with the WhatsApp channel, and then only way it would become unset is if the user explicitly cleared it?

**Comment by rudigiesler** [comment]
I haven't had a look at the code, but this doesn't seem to be happening in practice.

That could be another place to set it, when the contact is created on the first interaction, although that won't account for the case where contacts are created through an upload/API.

**Comment by rudigiesler** [comment]
Having a brief look at the code, it seems like we'll need to add a call to `WithContactName` to https://github.com/nyaruka/courier/blob/master/handlers/whatsapp/whatsapp.go#L178 to acheive the "add name when contact is created" option, is that correct?

**Comment by rowanseymour** [comment]
Yeah as long as the org isn't anon.. we should create contacts with any name provided by the channel that they first message us on.

**Comment by nicpottier** [comment]
Fixed in https://github.com/nyaruka/courier/pull/261
