### ISSUE TITLE
Incoming messages creating duplicate contact

### ISSUE THREAD

**Issue by erikh360** [nyaruka/courier#285]
Courier receives an incoming message over the WhatsApp channel for an existing contact but creates a new blank contact without urns to attach the message to, instead of adding it to the existing contact where the urn matches the incoming message's urn.

The new message is linked to the new duplicate contact while the contact_urn_id points to the correct urn. The modified_on field on the correct contact shows it was touched.

I don't see anything different for contacts or messages where this works or doesn't and it seems to be very intermittent. It happens very infrequently and on contacts that has been in the Rapidpro for a while. 

If I run the same queries that I see in the courier code it finds the correct contact. I've also tried to duplicate it on my local machine without success.

**Comment by nicpottier** [comment]
So as we chatted about, I sadly don't have a lot of clues for you on this and it is probably going to require some sleuthing on your side to find instances where this has occurred and maybe share the courier logs for those periods to see if there is anything telling. Is this occurring on a regular enough basis where you can predict it will happen in the next week? If so, maybe we can work together to add some extra logging to help figure out what is happening.

**Comment by erikh360** [comment]
It is pretty irregular and hard to predict. The last one was a few days ago, I'll wait for it to happen again to get some  logs. Thanks

**Comment by erikh360** [comment]
Sorry, scratch that, I was looking at the create date of the original contact in my query instead of the new duplicate. 

It happens every few minutes it seems.

from the logs it doesn't look much different than the others:
```
time="2020-03-23T08:49:11Z" level=info msg="msg received" channel_uuid=3e8008a9-d2ab-466f-ac99-eb146df51166 elapsed_ms=47.503971 msg_attachments="[]" msg_id=12663610 msg_text=Yes msg_urn="whatsapp:277<redacted>" msg_uuid=c0105997-fd30-4123-a9e5-acbcbdd3612c url=/c/wa/3e8008a9-d2ab-466f-ac99-eb146df51166/receive
time="2020-03-23T08:49:11Z" level=info msg="status committer bulk sql complete" elapsed=15.366193ms rows=1
time="2020-03-23T08:49:11Z" level=info msg="log committer bulk sql complete" elapsed=34.305436ms rows=12
```

**Comment by nicpottier** [comment]
If you look at the channel log for that contact/msg were there other events delivered around the same time? If you can share the channel log contents (redacted of course) for the two contacts created then maybe that could help us reason about what is happening.

One thought is that maybe the bulk committing pipeline is part of the problem here for status updates.

**Comment by erikh360** [comment]
There is a lot happening around the incoming message. 

Channel Log:
<img width="1531" alt="Screenshot 2020-03-24 at 11 24 55" src="https://user-images.githubusercontent.com/21120463/77411137-9f309400-6dc4-11ea-9bfe-988cea292c49.png">

Channel log details of incoming message:
<img width="1645" alt="Screenshot 2020-03-24 at 11 29 34" src="https://user-images.githubusercontent.com/21120463/77411188-b1aacd80-6dc4-11ea-9b8e-4770c6638ecd.png">

**Comment by nicpottier** [comment]
That list of channel logs is all the same contact? I'm more interested in whether a status message in right at the same time for example. Or whether there were two incoming messages at identical times.

**Comment by erikh360** [comment]
I hope this helps:
[Rapidpro_Message_Contact_mismatch_2020_03_25.xlsx](https://github.com/nyaruka/courier/files/4379757/Rapidpro_Message_Contact_mismatch_2020_03_25.xlsx)

**Comment by nicpottier** [comment]
Are you sending to the WhatsApp channel through another medium than RapidPro as well? IE, is Courier doing all the sending or are you also sending with something else?

**Comment by erikh360** [comment]
Everything is going through the Rapidpro WhatsApp channel using courier. There is only one channel configured.

The channel is connected through turn which is an exact copy of the WA API.

**Comment by nicpottier** [comment]
And those are all the first messages on that contact? Just wondering why we are seeing status messages before we ever send or receive a message.

**Comment by erikh360** [comment]
I think I might have misunderstood what you asked for, those are all the channel log events before and after the incoming message, not filtered by contact.

Let me see if I can filter by contacts, and get you a new export.

Some examples I've looked at actually previously received a message properly, then on the next one a duplicate contact was created.

**Comment by nicpottier** [comment]
Ya, I doubt it is a problem across contacts (though it's never what you think!). My guess would be that it is more something about receiving two messages or statuses near each other.

Any chance there is some number normalization taking place on your side vis-a-vis WhatsApp? see: https://github.com/nyaruka/courier/pull/287

**Comment by erikh360** [comment]
I looked at a few examples now and I can't find any where there are events/messages from the same contact or duplicate close to the message that causes the issue. 

We also don't do any number normalisation that I know of.

**Comment by nicpottier** [comment]
Hmm.. mind sharing the query you are using to find these contacts? Maybe we have some and I can look at things there.

**Comment by erikh360** [comment]
Here you go, you'll just need to add your org_id in there. Thanks for the help so far.

```
SELECT contacts_contact.created_on AS original_created_on,
       contacts_contact.id AS original_id,
       contacts_contact.uuid AS original_uuid,
       msgs_contacts_contact.created_on AS duplicate_created_on,
       msgs_contacts_contact.id AS duplicate_id,
       msgs_contacts_contact.uuid AS duplicate_uuid,
       msgs_msg.created_on AS msg_created_on,
       msgs_msg.id AS msg_id,
       msgs_msg.uuid AS msg_uuid
FROM msgs_msg,
     contacts_contacturn,
     contacts_contact,
     contacts_contact AS msgs_contacts_contact
WHERE msgs_msg.contact_urn_id = contacts_contacturn.id
  AND contacts_contacturn.contact_id = contacts_contact.id
  AND contacts_contact.id != msgs_msg.contact_id
  AND msgs_msg.contact_id = msgs_contacts_contact.id
  AND msgs_msg.org_id = 5
  AND msgs_msg.direction = 'I'
  AND (contacts_contact.created_on > now() - interval '1 hour'
       OR msgs_contacts_contact.created_on > now() - interval '1 hour')
ORDER BY msgs_contacts_contact.created_on DESC LIMIT 10;
```

**Comment by nicpottier** [comment]
Hrmm. So that query doesn't ever return on our DB, but I checked out highest WhatsApp org which has done ~400k messages in the past day and checked all contacts created in the past two days (~4k or so) and I don't see any which either don't have a URN or have msgs that don't match the URN they have.

So that makes me wonder if there is something to your config that could be causing this. Are you running anything between Courier and Postgres per chance?

**Comment by erikh360** [comment]
Hi Nic, sorry for the late reply, we found the issue, it was in our data from an import we did.

Thanks for the help!

**Comment by nicpottier** [comment]
Oh, well good!
