### ISSUE TITLE
Facebook API Version

### ISSUE THREAD

**Issue by tybritten** [nyaruka/courier#300]
The current facebook handler is pointed at the `v2.12` version of the API. I'm checking for breaking changes, but there doesn't seem to be any between that and `v6` which we could switch to and relieve the nag messages from FB about using a deprecating API version.

**Comment by nicpottier** [comment]
Ya, we're looking into this. May have to move up to 3.2 which should get us to next year as we have some things that need changing otherwise. We are in the process of changing how this integration works entirely, so don't want to invest too much into it.

**Comment by nicpottier** [comment]
Fixed in https://github.com/nyaruka/courier/pull/302
