### ISSUE TITLE
Bot loops

### ISSUE THREAD

**Issue by caioreix** [nyaruka/courier#345]
Many bots are talking to each other, and the current way to check this interaction created in the issue [#rapidpro/issues/1018](https://github.com/rapidpro/rapidpro/issues/1018) Is not being very effective, we've experience several enterprise bots that each new message offers a different answer, others that put the time that the message was sent and some even the number of interactions carried out. Some possible solution that I think to solve this, is checking the response time, if many messages were sent in a short period of time put the conversation in a “corner” like a wait list and alert an ADM to check the conversation.

**Comment by rowanseymour** [comment]
This now happens in mailroom - and will soon create a notification that users will see in the UI
