### ISSUE TITLE
Send to broadcast endpoints

### ISSUE THREAD

**Issue by caioreix** [nyaruka/courier#346]
We would like to know if the courier has the possibility to place orders with a list of contacts by checking if it is an array of contacts and encapsulating them in a slice and making requests to a broadcast endpoint instead of individual requests. The messangi channel is asking us for this type of practice because, as we are doing now, it is overloading its API.

**Comment by rowanseymour** [comment]
Mailroom and RapidPro queue messages individually and Courier works thru those queues in a way that is fair to different orgs. Even if you optimized Courier to batch up similar messages, or added batching somewhere between Courier and Messangi, that's still only going to help for the case when messages are identical. If the message starts with `Hi @contact, ...` it's not going to help.

**Comment by nicpottier** [comment]
We do not. You can however tune the rate that Courier sends messages on a channel by changing the `tps` (transactions per second) on that channel. That should let you deal with providers that can't deal with the volume.
