### ISSUE TITLE
WhatsApp - Excel being sent as .zip

### ISSUE THREAD

**Issue by rafaelbreno** [nyaruka/courier#353]
I've opened a ticket with WhatsApp reporting a "bug" that was converting Excel files to ".zip" when sending the document via API, the thing was, looks like courier is missing a field to define the file's name it's only setting the "caption", for example:

```go
// handlers/whatsapp.go

// Line: 110k
Document *struct {
    File     string `json:"file"      validate:"required"`
    ID       string `json:"id"        validate:"required"`
    Link     string `json:"link"`
    MimeType string `json:"mime_type" validate:"required"`
    Sha256   string `json:"sha256"    validate:"required"`
    Caption  string `json:"caption"`
    Filename string `json:"filename"` // Would add this
}

type mediaObject struct {
    ID       string `json:"id,omitempty"`
    Link     string `json:"link,omitempty"`
    Caption  string `json:"caption,omitempty"`
    Filename string `json:"filename,omitempty"`
}

// And would be possible do re-utilize the Caption to the Filename
// Line 475
if attachmentCount == 0 {
    mediaPayload.Caption = msg.Text()
    mediaPayload.Filename = msg.Text()
}
```

I think this would be one of the possible solutions, because wouldn't need to modify any other service(rapidpro/mailroom), more details about the "filename" field: [Facebook Docs](https://developers.facebook.com/docs/whatsapp/api/messages/media/).

Or even create a parser for the message text, something like:
```go
// I think this is a silly idea

// msg.Text() = "caption: UPartners list\nfilename: upartner.xlsx"
func (m *mediaObject) setCaptionFilename(msg string) {
	// Would need to have both fields "caption" and "filename"
	r := regexp.MustCompile(`(caption|filename)(:)[^\n]{1,}`)
	
	// Saving every match into []string
	strs := r.FindAllString(msg, -1)
	
	// Parsing through each string
	for _, str := range strs {
		
		// For filename Prefix
		// There's a condition, if for some reason the user decides to add 2 "filename" would only consider the first one
		if strings.HasPrefix(str, "filename:") && m.Filename == "" {
			m.Filename = strings.ReplaceAll(str, "filename: ", "")
			continue
		}
		
		// The same for Caption
		if strings.HasPrefix(str, "caption: ") && m.Caption == "" {
			m.Caption = strings.ReplaceAll(str, "caption: ", "")
			continue
		}
	}
}

// [...]
// Now implementing it into mediaPayload
// Line 475
if attachmentCount == 0 {
    mediaPayload.setCaptionFilename(msg.Text())
}
```

**Comment by nicpottier** [comment]
Have you tried this? Does it make a difference?

**Comment by rafaelbreno** [comment]
@nicpottier yep it does, when sending over Microsoft Office files(`.xlsx`, `.docx`, `.pptx`) it is received as `undefined.zip` file, if implement this solution it would be "sacrificing" the Caption but saving the File's type, because most of the users won't (or don't want to) know how to rename the file in their phone.

Other possible option could be adding a "filename" field when uploading a attachment into "Send Message" on Flow, so we would have both `Caption` and `Filename`
