### ISSUE TITLE
Incorrect Gujarati language code on WhatsApp templates

### ISSUE THREAD

**Issue by paulobernardoaf** [nyaruka/courier#403]
For the Gujarati language, the Facebook language code is `gu`.
When courier maps the language from iso639-3/iso3166-2 to WA language code, [it uses `gul` as the key](https://github.com/nyaruka/courier/blob/main/handlers/whatsapp/whatsapp.go#L1101).
But the `pycountry` lib uses  `guj` as language code key. 
Leading to a mismatch so templates in this language are not sent properly.
The issue is also in the rapidpro backend, at the template sync language mapping, [where it maps `gu` into `gul`](https://github.com/nyaruka/rapidpro/blob/main/temba/utils/whatsapp/constants.py#L35).

**Comment by matmsa27** [comment]
Hi @rowanseymour , did you have problems like that?

**Comment by norkans7** [comment]
This looks like a bug, I think `gul` should be changed to `guj`

**Comment by norkans7** [comment]
We need the rapidpro PR as well

**Comment by matmsa27** [comment]
Ya, we open a PR on Rapidpro too. Thanks @norkans7
