### ISSUE TITLE
Migrate WhatsApp to Cloud API

### ISSUE THREAD

**Issue by ericnewcomer** [nyaruka/courier#412]
From what I can tell, the only downside is Facebook can see the messages, whereas the container version is encrypted before it makes its way to Facebook. As such there is a message to this effect in the little blurb that usually says E2E but will say "This company uses a secures service from Meta to provide this service" or similar.

On the plus side, they charge nothing for this and we would no longer need to keep changing containers for API versions, no more EC2 instances, no more WhatsApp db cluster, etc. Seems worth it.

More on disclaimer here:
https://faq.whatsapp.com/general/security-and-privacy/why-am-i-seeing-a-new-system-message-in-my-whatsapp-chats

Cloud API
https://developers.facebook.com/docs/whatsapp/cloud-api

Postman docs
https://documenter.getpostman.com/view/13382743/UVC5FTHT

Looks like only beta access so far, not sure how to even apply for that.

**Comment by Robi9** [comment]
I started studying the Cloud API in addition to seeing the PR #430 and managed to gather some important points about the new integration.
I've been thinking about the app that the three types will share (FBA, IG and WAC), I think the strongest negative point in relation to this is the fact that the app can have a problem and end up causing the three channels to stop. I would also like to know about creating channels (WAC) in Rapidpro, will a new channel be added for support? Will they use Embedded Sign Up for the channel creation process?

**Comment by norkans7** [comment]
A new channel type will be added (WAC) and it will use the embedded signup pipeline.

I think using one single app is enough for all is enough and request the permissions and review once, any other limitations you might have noticed?
