### ISSUE TITLE
Some contacts are being "duplicated" in orgs with whatsapp channel

### ISSUE THREAD

**Issue by rasoro** [nyaruka/courier#433]
scenery:
if you add a contact with whatsapp identifier 5582**9**99448232 and send a template message to that contact, when he replies a new contact with whatsapp identifier 558299448232 is created, because his `wa_id` does not have this additional 9.

context:
here in brazil in 2016 all mobile phone numbers needed to have this additional 9 to make calls, and many whatsapp contacts here created before that date have their wa_id without this 9.

suggestion:
I think when sending a message to a contact, we could check after request response if URN.path is different from the wa_id, if so update the contact's URN appropriately.

observation of a message being sent to this contact:
![Captura de tela de 2022-04-14 11-28-56](https://user-images.githubusercontent.com/75167930/163411954-f800de4a-d0f5-4327-b129-efd1ddf3734f.png)

**Comment by matmsa27** [comment]
Hi @rowanseymour , what are your thoughts about this?

**Comment by rowanseymour** [comment]
This is a tricky one but it does seem like we should be storing the version _without the extra 9_ if that is the contact's actual WhatsApp ID, even tho that then makes for [an invalid phone number](https://libphonenumber.appspot.com/phonenumberparser?number=%2B558299448232&country=BR).

And since contacts will always give their "WhatsApp number" with the extra 9 we need to fix that after the fact. Does sounds like we need to fix it when sending.

I'm not the most familiar with the WhatsApp API.. can they also be fixed in the `refresh_whatsapp_contacts` task?

@norkans7 @ericnewcomer

**Comment by norkans7** [comment]
When we send a message to a contact and that fails we check the contact

https://github.com/nyaruka/courier/blob/5834bc2fb9789326d201b25ec373ab9e599bfb02/handlers/whatsapp/whatsapp.go#L953-L966

I am curious to know which number used when the contact replies to the channel, I would expect WA to send MO message using the wa_ID 558299448232 which is the one the accept us sending with.

Otherwise I think if whatsapp is sending in with 5582999448232 but only accept us sending with 558299448232 only, we always create a second contact for the incoming, not sure how to address this as we need to sort of have both at the same time.

Also we do not rely on the phone numbers for WhatsApp URNs

**Comment by rasoro** [comment]
When we send a message to contact the extra 9 on the number, it doesn't fail.

But when the contact sends a message to the channel, the event that arrives at the courier is handled based on the URN assembled from the wa_id of the contact who sent it. As it does not find the contact, a new one is created.

**Comment by norkans7** [comment]
So we are able to send to both 5582999448232 and 558299448232  without updating the URN before the PR changes
I really believe we update to the proper wa_id from the `checkWhatsAppContact`

Can you provide logs for the MO messages for such numbers?

**Comment by rasoro** [comment]
Starting a flow, and sending a message from rapidpro to contact

POST /v1/messages HTTP/1.1
Host: ...
User-Agent: Courier/Dev
Content-Length: 58
Accept: application/json
Authorization: Bearer ...
Content-Type: application/json
Accept-Encoding: gzip
```
{"to":"5582999448232","type":"text","text":{"body":"opa"}}
```       
HTTP/2.0 201 Created
Content-Length: 163
Cache-Control: private, must-revalidate
Content-Type: application/json
Date: Mon, 25 Apr 2022 15:01:22 GMT
Expires: -1
Pragma: no-cache
Server: nginx/1.19.10
X-Internal-Request-Ids: 86f8a3dc03c74593a61ddfbfeb8df4c4
X-Request-Id: 4e2b68bb3b3945c68410084398a62978
```
{"contacts":[{"input":"5582999448232","wa_id":"558299448232"}],"messages":[{"id":"gBEGVYKZRIIyAgkfhaCAxW_pRhk"}],"meta":{"api_status":"stable","version":"2.39.3"}}
```

**Comment by rasoro** [comment]
when the contact responds

POST /c/wa/16f9db5d-e2b8-4b17-a694-f984019c22b4/receive HTTP/1.0
Host: b91c-186-235-156-219.ngrok.io
Connection: close
Accept-Encoding: gzip, deflate
Accept-Language: en,*
Connection: close
Content-Length: 434
Content-Type: application/json
User-Agent: Mozilla/5.0
X-Forwarded-For: 34.255.194.28
X-Forwarded-Proto: https
X-Request-Id: 3F86B34CB2C454EB90470A7C05B4E036
X-Wa-Account-Id: 558231420901
```
{
    "contacts": [
        {
            "profile": {
                "name": "Rafa Soares"
            },
            "wa_id": "558299448232"
        }
    ],
    "messages": [
        {
            "from": "558299448232",
            "id": "ABEGVYKZRIIyAhA_hrNMssRU65BHCnwFtOA2",
            "text": {
                "body": "Eae"
            },
            "timestamp": "1650898893",
            "type": "text"
        }
    ]
}
```

HTTP/1.1 200 OK
Content-Encoding: gzip
Content-Type: application/json
Vary: Accept-Encoding

```
{"message":"Events Handled","data":[{"type":"msg","channel_uuid":"16f9db5d-e2b8-4b17-a694-f984019c22b4","msg_uuid":"80a86b0c-1b0e-4935-8396-102b3ed1e7b5","text":"Eae","urn":"whatsapp:558299448232","external_id":"ABEGVYKZRIIyAhA_hrNMssRU65BHCnwFtOA2","received_on":"2022-04-25T15:01:33Z"}]}
```

**Comment by rasoro** [comment]
it doesn't update because there is no error so it doesn't enter the if block that call the `checkWhatsAppContact`

![Captura de tela de 2022-04-25 12-45-24](https://user-images.githubusercontent.com/75167930/165125444-a4391785-51ac-4ddc-9d84-2e7a4d53696a.png)

**Comment by rasoro** [comment]
sorry for the lack of details i should have included all this information at the beginning.

**Comment by norkans7** [comment]
My last question is how was the contact "Rafael" got created?
Is that my a message from the WhatsApp contact to RapidPro? If so I think we can still have have the contact being duplicated

**Comment by rasoro** [comment]
Rafael was created by the create contact form, and then edited to add the whatsapp identifier.

**Comment by norkans7** [comment]
We can still end up with a duplicate contact by the phone sending us a message when we have a contact created manually with the old format but with the PR we'll steal the correct URN, I guess that will be fine as the other contact will stay without URN

**Comment by rasoro** [comment]
I believe the big benefit of PR is that the correct URN remains with the initial contact, who may likely have a history within the system from other channels.

Guys, thank you very much for your patience and support.
