### ISSUE TITLE
Line feature parity

### ISSUE THREAD

**Issue by ericnewcomer** [nyaruka/courier#452]
Line needs a pass to make sure the experience is on par with other chat channel types. I know at the very least quick replies are missing, but we should also make sure everything is at least as good as Telegram and WhatsApp when it comes to attachments, etc.

**Comment by norkans7** [comment]
https://github.com/nyaruka/courier/pull/453

https://github.com/nyaruka/courier/pull/454

**Comment by norkans7** [comment]
For outgoing messages(MT), the attachments we currently support are images only

To support videos, we need a way to manage a preview Image 
https://developers.line.biz/en/reference/messaging-api/#video-message

And for audio, we need to convert audios to M4A format and pass the duration 
https://developers.line.biz/en/reference/messaging-api/#audio-message

No way to pass a document as attachment

Currently, we send a URL for the attachment as text for all the 3 cases.
https://github.com/nyaruka/courier/blob/3c5b08c9e7029028d1b59dacc45f29ebdb02f325/handlers/line/line.go#L316
