### ISSUE TITLE
Support for sending attachments with captions

### ISSUE THREAD

**Issue by Robi9** [nyaruka/courier#456]
Hello everyone, I would like us to discuss the way in which the sending of attachments with text in the `WAC` type channel is handled.
We saw that the text of attachments can be sent as a caption, which could make it even more intuitive for the user. The way it is done today, sending the attachment first and then sending the text message, could be improved by adding the use of captions.
I know that the way currently used was thought about the maximum size of the message, but what if we did a check on the size of the text that we could send it as a caption if it is less than or equal to the maximum size of the text, or send it separately of the attachment, the way it is done today when it becomes larger than the maximum size.
I brought up these questions because we saw that this change will impact quick replies and lists replies that have text and attachment since the message sending payload assembly function in the handler was built based on these separate sends. Can we discuss this further?

**Comment by matmsa27** [comment]
Hi, @rowanseymour and @norkans7 what are your thoughts about this improvement on whats app cloud handler?

**Comment by norkans7** [comment]
Sounds good, please open a PR for that.
It is not clear to me how that affect the quick replies though or how the quick replies have attachments we'll see with those changes
