### ISSUE TITLE
Attachment fetching should give up eventually

### ISSUE THREAD

**Issue by ericnewcomer** [nyaruka/courier#538]
A WAC channel in production has been trying very hard to fetch attachments but getting 404s and never giving up.

Related sentry:
https://sentry.io/organizations/nyaruka/issues/3679947247/?project=205725&query=is%3Aunresolved&referrer=issue-stream

**Comment by rowanseymour** [comment]
Guess in that cae we just have to handle the message without the attachments, but it would be nice if there was something on the message recorded that
