### ISSUE TITLE
Identify message language for List Message

### ISSUE THREAD

**Issue by Robi9** [nyaruka/courier#541]
Hello guys! I would like to ask a question about the language of the flows. Would there be any way for the courier to identify which language of the flow belongs to the current message? I ask this because in List Messages on the WAC and WA channels, sent when there are more than 3 quick replies, the word "Menu" is always sent as the title of the list, which makes a difference when the language is not English. Do you see any way of having the language as a message field, when the case of List Messages occurs, so that there could be a mapping for the word "Menu"?

**Comment by rowanseymour** [comment]
It makes sense - there's already a language property on `ivr_created` events.. we could add that to `msg_created` as well. 

And that can be part of the payload queued to courier... tho, so that it's correct for messages that error and are requeued, we should add it to the `Msg` model as well.

**Comment by Robi9** [comment]
@rowanseymour I started to understand more about how this mapping for `ivr_created` is done, I'm just in doubt about the `MsgOut` attribute in the mailroom that has `TextLanguage` which is the language of the contact, could you explain better where and how it is assigned this language in it? I saw that I will need it to perform the mapping.

**Comment by rowanseymour** [comment]
I've started work on some changes to add locale (language+country) to all messages more generally: https://github.com/nyaruka/mailroom/pull/2. I think we can add a locale column to the `msgs_msg` table so it's there for any channel type that needs it when sending.

In the case of outgoing messages from flows, we have language stored on the contact and we can infer country from their preferred channel or tel URNs.
