### ISSUE TITLE
WhatsApp status API change

### ISSUE THREAD

**Issue by rudigiesler** [nyaruka/courier#570]
From version `2.45` of the WhatsApp API, the `recipient_id` field will be removed from the webhook coming in from WhatsApp: https://developers.facebook.com/docs/whatsapp/on-premises/webhooks/components#statuses-object . 

This information is instead found in the new `message.recipient_id` part of the status. I can't find any documentation on the `message` key, besides the following example: https://developers.facebook.com/docs/whatsapp/on-premises/webhooks/outbound#status--message-sent

As far as I can tell, we're not using the `recipient_id`, but it is marked as required, which will cause the validation to fail. If it isn't required, then a fix should be as easy as removing that field from the struct.

**Comment by rowanseymour** [comment]
Not being used and was straightforward to remove https://github.com/nyaruka/courier/pull/571
