### ISSUE TITLE
Package name whatsapp is wrong

### ISSUE THREAD

**Issue by vctrferreira** [nyaruka/courier#66]
Hey guys, I was looking the code of courier and I saw that @nicpottier made a simple mistake in whatsapp handler package name, this package it is called by **`telegram`** and I think that name of this package should be called by **`whastapp`**.

package path:
https://github.com/nyaruka/courier/tree/master/handlers/whatsapp

**Comment by nicpottier** [comment]
Right you are! Fixed in https://github.com/nyaruka/courier/commit/df1cbaa0a8f3e09889e4f62ad98a40563ade03e4
